version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 14...
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
      - echo Installing npm...
      - curl -L https://npmjs.org/install.sh | sudo sh
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist